[package]
name = "cortex_generation"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
cortex = { path = "../cortex" }
convert_case = "0.6"
quote = "1.0"


[dev-dependencies]
semver = "1.0"
